# Change these first
owner: meese-enterprises # Your GitHub organization or username, where this repository lives
repo: uptime-monitor # The name of this repository

sites:
  - name: Meese Enterprises
    url: https://meese.enterprises
    icon: https://raw.githubusercontent.com/meese-enterprises/website/master/logo.png
  - name: MeeseOS
    url: https://aaronmeese.com
    icon: https://raw.githubusercontent.com/ajmeese7/aaronmeese.com/master/website/src/client/aaron.png
  - name: Capture the Flag
    url: https://aaronmeese.dev
    # TODO: Pick an icon for this URL
    icon: https://raw.githubusercontent.com/ajmeese7/aaronmeese.com/master/website/src/client/aaron.png
  - name: KaraOS
    url: https://karameese.com
    icon: https://raw.githubusercontent.com/ajmeese7/karameese.com/master/logo.png

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime-monitor
  logoUrl: https://avatars.githubusercontent.com/u/102113339?s=200&v=4
  name: Meese Enterprises Uptime Monitor
  introTitle: "Courtesy of **Upptime**, the open-source uptime monitor and status page powered entirely by GitHub."
  introMessage: This site is used to display a history of the real-time status of public sites falling under the Meese Enterprises umbrella.
  navbar:
    - title: Status
      href: /$REPO
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
